### ISSUE TITLE
Apresentar estado de erro na tela de login

### ISSUE THREAD

**Issue by wilcorrea** [devitools/laravel-quasar-starter-kit#8]

**Comment by iguit0** [comment]
## :anger: Traduzir mensagens de erro na tentativa de login

⏯️ Como reproduzir:

- Entrar na [demo](https://demo.devi.tools)
- Sem preencher usuário e senha, clicar em **ENTRAR**

### Resultado :point_down:

![error_login_auth](https://user-images.githubusercontent.com/12905770/87075097-35fb5200-c1f6-11ea-8c36-0556c7de7c62.jpg)

**Comment by iguit0** [comment]
## :anger: Adicionar um botão para voltar ao login

⏯️ Como reproduzir:

- Entrar na [demo](https://demo.devi.tools)
- Clicar em **QUERO ME CADASTRAR** na parte inferior do formulário

### Resultado :point_down:

![botao_voltar_login](https://user-images.githubusercontent.com/12905770/87075787-3d6f2b00-c1f7-11ea-994e-b9fdc7bd2370.png)

**Comment by iguit0** [comment]
## :anger: Mensagem de validação do toast desconfigurada ao tentar realizar login

⏯️ Como reproduzir:

- Entrar na [demo](https://demo.devi.tools)
- Sem preencher usuário e senha, clicar em **ENTRAR**
- Observar a mensagem na parte superior direita

### Resultado :point_down:

![toast_message](https://user-images.githubusercontent.com/12905770/87076051-98088700-c1f7-11ea-9153-75484b94a21d.jpg)
